import type {Metadata, Viewport} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from 'react';
import CommonLayout from "@/app/commonLayout";
import { ThemeProvider } from 'next-themes'

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    minimumScale: 1,
    userScalable: false,
}

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider>
                    <CommonLayout>
                        {children}
                    </CommonLayout>
                </ThemeProvider>
            </body>
        </html>
    )
}



